#!/bin/sh
version=$(curl -s -B "http://cloud.github.com/downloads/intelie/lognit-cli/VERSIONS" 2>/dev/null)
echo Installing Lognit command-line interface v$version
curl http://cloud.github.com/downloads/intelie/lognit-cli/lognit-cli-$version.sh > /usr/bin/nit
chmod a+x /usr/bin/nit
