#!/bin/sh
if [ $# -lt 2 ]; then
    echo 'release <current> <next>'
    echo 'release 1.0 1.1'
    exit 0
fi
mvn versions:set -DnewVersion=$1
git commit -am "release version $1"
git tag $1
git push --tags
mvn versions:set -DnewVersion=$2-SNAPSHOT
git commit -am "next version $2-SNAPSHOT"
